version: "3.8"
services:
  personal_portfolio:
    container_name: personal_portfolio
    image: my-portfolio
    build: 
      context: .
      target: production
    working_dir: /usr
    restart: always
    env_file:
      - ./.env.production.local
    ports:
      - 3080:80
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - my-portfolio

networks:
  my-portfolio:
    external: false
    name: my-portfolio